Schweppesale\Module\Access\Domain\Entities\Role:
    type: entity
    table: roles
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: created_at
        name:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        sort:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: updated_at
    manyToMany:
        permissions:
            targetEntity: Schweppesale\Module\Access\Domain\Entities\Permission
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinTable:
                name: permission_role
                schema: null
                joinColumns:
                    -
                        name: role_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: permission_id
                        unique: true
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
        users:
            targetEntity: Schweppesale\Module\Access\Domain\Entities\User
            cascade: {  }
            fetch: LAZY
            mappedBy: roles
            inversedBy: null
            joinTable:
                name: assigned_roles
                schema: null
                joinColumns:
                    -
                        name: role_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: user_id
                        unique: true
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
