Schweppesale\Module\Access\Application\Response\GroupDTO:
    properties:
        parentId:
            exclude: true
        permissionIds:
            exclude: true
    relations:
        -
            rel: self
            href:
                route: groups.show
                parameters:
                    user: expr(object.getId())
                absolute: true
        -
            rel: parent
            href:
                route: groups.show
                parameters:
                    group: expr(object.getParentId())
                absolute: true
            exclusion:
                exclude_if: expr(object.getParentId() == false)
        -
            rel: permissions
            href:
                route: permissions.group.index
                parameters:
                    group: expr(object.getId())
                absolute: true
            exclusion:
                exclude_if: expr(object.getPermissionIds() == false)
        -