Schweppesale\Module\Access\Application\Response\PermissionDTO:
    properties:
        dependencyIds:
            exclude: true
        groupId:
            exclude: true
        userIds:
            exclude: true
        roleIds:
            exclude: true
    relations:
        -
            rel: self
            href:
                route: permissions.show
                parameters:
                    user: expr(object.getId())
                absolute: true
        -
            rel: dependencies
            href:
                route: dependencies.permission.index
                parameters:
                    permission: expr(object.getId())
                absolute: true
            exclusion:
                exclude_if: expr(object.getDependencyIds() == false)
        -
            rel: group
            href:
                route: groups.show
                parameters:
                    user: expr(object.getGroupId())
                absolute: true
            exclusion:
                exclude_if: expr(object.getGroupId() == false)
        -
            rel: users
            href:
                route: users.permission.index
                parameters:
                    user: expr(object.getId())
                absolute: true
            exclusion:
                exclude_if: expr(object.getUserIds() == false)
        -
            rel: roles
            href:
                route: roles.permission.index
                parameters:
                    user: expr(object.getId())
                absolute: true
            exclusion:
                exclude_if: expr(object.getRoleIds() == false)
