Schweppesale\Module\Access\Application\Response\RoleDTO:
    properties:
        permissionIds:
            exclude: true
    relations:
        -
            rel: self
            href:
                route: roles.show
                parameters:
                    user: expr(object.getId())
                absolute: true
        -
            rel: permissions
            href:
                route: permissions.role.index
                parameters:
                    role: expr(object.getId())
                absolute: true
            exclusion:
                exclude_if: expr(object.getPermissionIds() == false)
