Schweppesale\Module\Access\Application\Response\GroupDTO:
    properties:
        permissions:
            exclude: true
        parent:
            exclude: true
    relations:
        -
            rel: self
            href:
                route: groups.show
                parameters:
                    user: expr(object.getId())
                absolute: true
        -
            rel: parent
            embedded:
                content: expr(object.getParent())
                xmlElementName: role
            exclusion:
                exclude_if: expr(object.getParent() == false)
        -