Schweppesale\Module\Access\Application\Response\UserDTO:
    properties:
        permissionIds:
            exclude: true
        roleIds:
            exclude: true
    relations:
        -
            rel: self
            href:
                route: users.show
                parameters:
                    user: expr(object.getId())
                absolute: true
        -
            rel: roles
            href:
                route: roles.user.index
                parameters:
                    roles: expr(object.getId())
                absolute: true
            exclusion:
                exclude_if: expr(object.getRoleIds() == false)
        -
            rel: permissions
            href:
                route: permissions.user.index
                parameters:
                    permission: expr(object.getId())
                absolute: true
            exclusion:
                exclude_if: expr(object.getPermissionIds() == false)
        -